=== Ixf2/V-lcanes_XML_y_DTD/Activity11-JoanaRamirez.dtd
<!ELEMENT CanaryIsland (volcanos)>
<!ELEMENT volcanos (volcano*)>
<!ELEMENT volcano (affected_area*, resource)>
<!ATTLIST volcano 
    name_island CDATA #REQUIRED
    start_date CDATA #REQUIRED
    final_date CDATA #REQUIRED>
<!ELEMENT affected_area (zones, municipalities)>
<!ELEMENT material (#PCDATA)>
<!ATTLIST material und CDATA #REQUIRED>
<!ELEMENT zones (zone*)>
<!ELEMENT zone (#PCDATA)>
<!ELEMENT municipalities (municipality*)>
<!ELEMENT municipality (emergencyPhones, civil_service?)>
<!ATTLIST municipality name_municipality CDATA #REQUIRED>
<!ELEMENT emergencyPhones (emergencyPhone*)>
<!ELEMENT emergencyPhone (#PCDATA)>
<!ELEMENT civil_service (#PCDATA)>
<!ELEMENT resource (material, humans)>
<!ELEMENT material (#PCDATA)>
<!ELEMENT humans (human*)>
<!ELEMENT human (task+)>
<!ATTLIST human 
    name_human CDATA #REQUIRED
    surname_human CDATA #REQUIRED
    dni CDATA #REQUIRED>
<!ELEMENT task (#PCDATA)>
<!ATTLIST task 
    date_task CDATA #REQUIRED
    hour CDATA #REQUIRED>

=== Ixf2/V-lcanes_XML_y_DTD/Activity11-JoanaRamirez.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE CanaryIsland SYSTEM "Activity11-JoanaRamirez.dtd">
<CanaryIsland>
    <volcanos>
        <volcano name_island = "La Palma" start_date ="19-09-2001" final_date="12-12-2001">
            <affected_area>
                <zones>
                    <zone>Todoque</zone>
                </zones>
                <municipalities>
                    <municipality name_municipality="Los Llanos de Aridane">
                        <emergencyPhones>
                            <emergencyPhone>123123123</emergencyPhone>
                        </emergencyPhones>
                        <civil_service>23</civil_service>
                    </municipality>
                </municipalities>
            </affected_area>
            <resource>
                <material und="5">Helicopter</material>
                <humans>
                    <human name_human="Juan" surname_human="Rodriguez" dni="12121212D">
                        <task date_task="19-09-2001" hour="3h">Ayudante en la evacuaci√≥n de los habitantes de Todoque</task>
                    </human>
                </humans>
            </resource>
        </volcano>
    </volcanos>
</CanaryIsland>
